Fix another old-style set-output
cisagov/skeleton-tf-module pull request #37
Opened 2020-10-09 21:35 UTC by jsf9k

## 🗣 Description

This pull request changes an old-style `set-output` to instead use `$GITHUB_ENV`.

## 💭 Motivation and Context

We now prefer the use of `$GITHUB_ENV` to this old way of doing things.

## 🧪 Testing

All pre-commit hooks pass.

## 🚥 Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2020-10-10 12:41 UTC, felddy approved these changes
Ya ya ya ya ya ya, ya-ya, yaaaa!!! [GO!](https://www.youtube.com/watch?v=3TJC48BRBn8) 🎶

2020-10-12 17:26 UTC, mcdonnnj requested changes
Thanks for catching this! However, if we're changing the way that value is referenced, then when it is used must be updated as well:
https://github.com/cisagov/skeleton-tf-module/blob/bcee6fac39651d3b2efecdf3dee8e7e841af66d2/.github/workflows/build.yml#L53
should be updated to refer to `env.GOCACHE_DIR`.

2020-10-12 17:34 UTC, jsf9k commented
> Thanks for catching this! However, if we're changing the way that value is referenced, then when it is used must be updated as well:
> https://github.com/cisagov/skeleton-tf-module/blob/bcee6fac39651d3b2efecdf3dee8e7e841af66d2/.github/workflows/build.yml#L53
> 
> 
> should be updated to refer to `env.GOCACHE_DIR`.

Thanks for catching that!  I did a force push that should correct the issue.  See commit 3e9e429.

2020-10-13 14:20 UTC, dav3r approved these changes
Cleanup on aisle 3! 👍

2020-10-13 14:52 UTC, mcdonnnj approved these changes
Lookin' good!

2020-10-13 15:44 UTC, merged